apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmr-agent-ui
  namespace: di-dta-gke
spec:
  selector:
    matchLabels:
      app: rmr-agent-ui
  replicas: 1
  template:
    metadata:
      labels:
        app: rmr-agent-ui
    spec:
      serviceAccountName: openalgplt
      containers:
        - name: rmr-agent
          image: "dockerhub.paypalcorp.com/dta-ces/rmr-agent-ui:0.1.0"
          ports:
            - containerPort: 8080
          env:
            - name: BASE_URL
              value: ''
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
      restartPolicy: Always